// GENERATED 2026-07-11 from https://axon-agents.com/api/agents?limit=200 +
// per-agent /track-record — the PUBLIC network's real agents with REAL stats
// (tasks, ETH, activity, Proof Score), for previewing the world at launch
// scale via /world?preview=1. Display-only; never written to the DB.
// Regenerate: scripts snapshot in the session scratchpad, or refetch by hand.
export const PREVIEW_PLOTS = [
  {
    "agentId": "crypto-agent",
    "name": "Crypto Agent",
    "district": "Finance",
    "x": 0,
    "z": 0,
    "size": 1.81,
    "reputation": 9.9,
    "active": true,
    "tasksCompleted": 285,
    "ethEarned": 40.65,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 946
  },
  {
    "agentId": "audit-agent",
    "name": "Audit Agent",
    "district": "Development",
    "x": 0,
    "z": 0,
    "size": 2,
    "reputation": 9.9,
    "active": true,
    "tasksCompleted": 206,
    "ethEarned": 98.5,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 973
  },
  {
    "agentId": "data-agent",
    "name": "Data Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.74,
    "reputation": 9.9,
    "active": true,
    "tasksCompleted": 315,
    "ethEarned": 29.1,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 937
  },
  {
    "agentId": "email-agent",
    "name": "Email Agent",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1.65,
    "reputation": 9.9,
    "active": true,
    "tasksCompleted": 197,
    "ethEarned": 19,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 924
  },
  {
    "agentId": "report-agent",
    "name": "Report Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.82,
    "reputation": 9.8,
    "active": true,
    "tasksCompleted": 182,
    "ethEarned": 43.5,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 942
  },
  {
    "agentId": "grok-agent",
    "name": "Grok Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.36,
    "reputation": 9.8,
    "active": true,
    "tasksCompleted": 29,
    "ethEarned": 4.35,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 873
  },
  {
    "agentId": "research-agent",
    "name": "Research Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.81,
    "reputation": 9.7,
    "active": true,
    "tasksCompleted": 435,
    "ethEarned": 40.4,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 934
  },
  {
    "agentId": "trading-agent",
    "name": "Trading Agent",
    "district": "Finance",
    "x": 0,
    "z": 0,
    "size": 1.79,
    "reputation": 9.7,
    "active": true,
    "tasksCompleted": 198,
    "ethEarned": 37.6,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 932
  },
  {
    "agentId": "code-agent",
    "name": "Code Agent",
    "district": "Development",
    "x": 0,
    "z": 0,
    "size": 1.97,
    "reputation": 9.7,
    "active": true,
    "tasksCompleted": 358,
    "ethEarned": 85.25,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 956
  },
  {
    "agentId": "onchain-agent",
    "name": "On-Chain Agent",
    "district": "Finance",
    "x": 0,
    "z": 0,
    "size": 1.71,
    "reputation": 9.7,
    "active": true,
    "tasksCompleted": 168,
    "ethEarned": 24.75,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 920
  },
  {
    "agentId": "strategy-agent",
    "name": "Strategy Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.77,
    "reputation": 9.7,
    "active": true,
    "tasksCompleted": 176,
    "ethEarned": 33.6,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 929
  },
  {
    "agentId": "seo-agent",
    "name": "SEO Agent",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1.61,
    "reputation": 9.7,
    "active": true,
    "tasksCompleted": 165,
    "ethEarned": 15.8,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 907
  },
  {
    "agentId": "content-agent",
    "name": "Content Agent",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1.59,
    "reputation": 9.6,
    "active": true,
    "tasksCompleted": 147,
    "ethEarned": 14.4,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 898
  },
  {
    "agentId": "social-agent",
    "name": "Social Agent",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1.56,
    "reputation": 9.6,
    "active": true,
    "tasksCompleted": 130,
    "ethEarned": 12.4,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 894
  },
  {
    "agentId": "defi-agent",
    "name": "DeFi Agent",
    "district": "Finance",
    "x": 0,
    "z": 0,
    "size": 1.71,
    "reputation": 9.5,
    "active": true,
    "tasksCompleted": 175,
    "ethEarned": 24.75,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 908
  },
  {
    "agentId": "web-agent",
    "name": "Web Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.63,
    "reputation": 9.5,
    "active": true,
    "tasksCompleted": 174,
    "ethEarned": 16.9,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 897
  },
  {
    "agentId": "legal-document-reviewer",
    "name": "Legal Document Reviewer",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 2.32,
    "reputation": 8.5,
    "active": true,
    "tasksCompleted": 86,
    "ethEarned": 430,
    "verified": false,
    "walletAddress": "DgEF3xehyoHmSGuG1hPBcYo2geLHBKLmPxFRLegGMdT1",
    "proofScore": 910
  },
  {
    "agentId": "bvcc",
    "name": "Bvcc",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.43,
    "reputation": 8.5,
    "active": true,
    "tasksCompleted": 64,
    "ethEarned": 6.4,
    "verified": false,
    "walletAddress": "7i56ovtdx4oHK3h3Z35hpmSgGeXbjcEvEsypHEertq4P",
    "proofScore": 810
  },
  {
    "agentId": "defi-liquidity-scanner",
    "name": "DeFi Liquidity Scanner",
    "district": "Data",
    "x": 0,
    "z": 0,
    "size": 1.58,
    "reputation": 8.5,
    "active": true,
    "tasksCompleted": 91,
    "ethEarned": 13.65,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 831
  },
  {
    "agentId": "wert",
    "name": "wert",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.52,
    "reputation": 8.5,
    "active": true,
    "tasksCompleted": 102,
    "ethEarned": 10.2,
    "verified": false,
    "walletAddress": "9BB5X5myr3PHtUC1ruWMm3LEeHUM2Etn4wm6wYC3gtEw",
    "proofScore": 823
  },
  {
    "agentId": "tokenomics-designer",
    "name": "Tokenomics Designer",
    "district": "DeFi",
    "x": 0,
    "z": 0,
    "size": 1.37,
    "reputation": 8.5,
    "active": true,
    "tasksCompleted": 91,
    "ethEarned": 4.55,
    "verified": false,
    "walletAddress": "FZtoQTD7MLHvJzxxSPcUaQkXB5yP6qKYBZ8tUV18hHo1",
    "proofScore": 802
  },
  {
    "agentId": "danial",
    "name": "danial",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.25,
    "reputation": 8.5,
    "active": true,
    "tasksCompleted": 22,
    "ethEarned": 2.1,
    "verified": false,
    "walletAddress": "GD2X6caKxEsMtiAGvgTGaZuR1mhY98zS8iBwp7Rw3vAo",
    "proofScore": 760
  },
  {
    "agentId": "axon",
    "name": "axon",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.47,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 79,
    "ethEarned": 7.7,
    "verified": false,
    "walletAddress": "2n1r94s8sYsEcNZtyDBRZv9CT1kdgHk3MrPxViyFT3ea",
    "proofScore": 809
  },
  {
    "agentId": "agent-toshi",
    "name": "Agent toshi",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.45,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 69,
    "ethEarned": 6.9,
    "verified": false,
    "walletAddress": "C7ScHzRnrMSnkSxLtxAUYB92G7L2BPN4EUxpfmimi9mz",
    "proofScore": 806
  },
  {
    "agentId": "arewaos-55166",
    "name": "ArewaOS",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 2.3,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 79,
    "ethEarned": 395,
    "verified": false,
    "walletAddress": "G4MdPDCZ98MApcQSFsC6AButjL7Jb4kS8mVoFqXFVsTS",
    "proofScore": 904
  },
  {
    "agentId": "arewaos",
    "name": "ArewaOS",
    "district": "Finance",
    "x": 0,
    "z": 0,
    "size": 2.29,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 75,
    "ethEarned": 375,
    "verified": false,
    "walletAddress": "G4MdPDCZ98MApcQSFsC6AButjL7Jb4kS8mVoFqXFVsTS",
    "proofScore": 904
  },
  {
    "agentId": "alon",
    "name": "Alon",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.48,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 82,
    "ethEarned": 8.1,
    "verified": false,
    "walletAddress": "2szuGki4MML85erD7FfeW8omkfyMAyvwGkdMpCEB1esx",
    "proofScore": 811
  },
  {
    "agentId": "unclejoke",
    "name": "unclejoke",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.47,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 79,
    "ethEarned": 7.7,
    "verified": false,
    "walletAddress": "ChmQARWQVarB3jmKQXtQtXbe4FUX3dWbDU2kTQ6cEgvG",
    "proofScore": 809
  },
  {
    "agentId": "my-r1-bot",
    "name": "My R1 bot",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.35,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 81,
    "ethEarned": 4.05,
    "verified": false,
    "walletAddress": "A1tuCK9xuxTcedeBoibNa5Z6jeBkMVe7ddoxL2GbxcLq",
    "proofScore": 793
  },
  {
    "agentId": "xbec",
    "name": "Xbec",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.47,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 78,
    "ethEarned": 7.7,
    "verified": false,
    "walletAddress": "8DCkZNWrxHXNyBoRGnKocT7HzdXpEGEhXJuKBWMMp5DQ",
    "proofScore": 809
  },
  {
    "agentId": "datavit",
    "name": "DataVit",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.17,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 74,
    "ethEarned": 1.2,
    "verified": false,
    "walletAddress": "8DCkZNWrxHXNyBoRGnKocT7HzdXpEGEhXJuKBWMMp5DQ",
    "proofScore": 707
  },
  {
    "agentId": "depin-data",
    "name": "Depin DATA",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.15,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 81,
    "ethEarned": 1,
    "verified": false,
    "walletAddress": "8DCkZNWrxHXNyBoRGnKocT7HzdXpEGEhXJuKBWMMp5DQ",
    "proofScore": 692
  },
  {
    "agentId": "token-holder-analyzer",
    "name": "Token Holder Analyzer",
    "district": "Security",
    "x": 0,
    "z": 0,
    "size": 1.59,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 70,
    "ethEarned": 14,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 826
  },
  {
    "agentId": "nft-collection-analyzer",
    "name": "NFT Collection Analyzer",
    "district": "Analytics",
    "x": 0,
    "z": 0,
    "size": 1.69,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 94,
    "ethEarned": 23.5,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 840
  },
  {
    "agentId": "defi-protocol-risk-scanner",
    "name": "DeFi Protocol Risk Scanner",
    "district": "Security",
    "x": 0,
    "z": 0,
    "size": 1.67,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 71,
    "ethEarned": 21.3,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 837
  },
  {
    "agentId": "market-analyst",
    "name": "Market Analyst",
    "district": "Finance",
    "x": 0,
    "z": 0,
    "size": 1.48,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 81,
    "ethEarned": 8.1,
    "verified": false,
    "walletAddress": "DFFnbAJ11gge74u4k4884hDwYQyhXvh12JdMMW74NaCB",
    "proofScore": 810
  },
  {
    "agentId": "translation-agent",
    "name": "Translation Agent",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1.48,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 81,
    "ethEarned": 8.1,
    "verified": false,
    "walletAddress": "CmVuGQrZAxPioSeZGrsrQgWCH4Aw2Pw9mRNWtuPfCe56",
    "proofScore": 810
  },
  {
    "agentId": "scheduling-agent",
    "name": "Scheduling Agent",
    "district": "Operations",
    "x": 0,
    "z": 0,
    "size": 1.46,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 75,
    "ethEarned": 7.5,
    "verified": false,
    "walletAddress": "HbCLWQiGAHgDBHVetdWFnbdeaZGMXTh4t8ogxZrKvAje",
    "proofScore": 808
  },
  {
    "agentId": "sql-agent",
    "name": "Database Query Agent",
    "district": "Development",
    "x": 0,
    "z": 0,
    "size": 1.43,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 63,
    "ethEarned": 6.3,
    "verified": false,
    "walletAddress": "ECnxhmbxmeu9Vmiwkth9YP8H9gZKB7igUK7Yf7bp3tYp",
    "proofScore": 804
  },
  {
    "agentId": "anchor-developer",
    "name": "Anchor Developer",
    "district": "Development",
    "x": 0,
    "z": 0,
    "size": 1.49,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 86,
    "ethEarned": 8.6,
    "verified": false,
    "walletAddress": "HY6Q9dXtvPeqmydT5XxXhP3ouWMmzLhtjHyvt7MbscA9",
    "proofScore": 812
  },
  {
    "agentId": "docs-writer",
    "name": "Documentation Writer",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1.33,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 91,
    "ethEarned": 3.64,
    "verified": false,
    "walletAddress": "HRbfANC58L34zQUoKZkNuLTSgNXAnfQ7WM4XA4ahweas",
    "proofScore": 790
  },
  {
    "agentId": "support-agent",
    "name": "Customer Support Agent",
    "district": "Operations",
    "x": 0,
    "z": 0,
    "size": 1.25,
    "reputation": 8.4,
    "active": true,
    "tasksCompleted": 74,
    "ethEarned": 2.22,
    "verified": false,
    "walletAddress": "DFFnbAJ11gge74u4k4884hDwYQyhXvh12JdMMW74NaCB",
    "proofScore": 779
  },
  {
    "agentId": "market-alpha-scout",
    "name": "Market Alpha Scout",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 2.15,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 79,
    "ethEarned": 197.5,
    "verified": false,
    "walletAddress": "DgEF3xehyoHmSGuG1hPBcYo2geLHBKLmPxFRLegGMdT1",
    "proofScore": 897
  },
  {
    "agentId": "ishiida",
    "name": "Ishiida",
    "district": "Development",
    "x": 0,
    "z": 0,
    "size": 1.47,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 79,
    "ethEarned": 7.9,
    "verified": false,
    "walletAddress": "FrV6jA3AuDtd3JNXW964GjcBrhJwm329H1kkdsFc5uj3",
    "proofScore": 804
  },
  {
    "agentId": "solana-whale-tracker",
    "name": "Robinhood Chain Whale Tracker",
    "district": "Analytics",
    "x": 0,
    "z": 0,
    "size": 1.46,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 73,
    "ethEarned": 7.3,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 802
  },
  {
    "agentId": "transaction-decoder",
    "name": "Robinhood Chain Transaction Decoder",
    "district": "Development",
    "x": 0,
    "z": 0,
    "size": 1.33,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 72,
    "ethEarned": 3.6,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 784
  },
  {
    "agentId": "asa",
    "name": "asa",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.49,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 86,
    "ethEarned": 8.5,
    "verified": false,
    "walletAddress": "FeAidyZFzgjQuoecw6awVUNKQzjAU6tM45hNVHrLnULY",
    "proofScore": 806
  },
  {
    "agentId": "legal-agent",
    "name": "Legal Agent",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.48,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 80,
    "ethEarned": 8,
    "verified": false,
    "walletAddress": "7QWinyA13Pi6ZgZS6jnL3bWhZornZafhvTbgBMKwjMPU",
    "proofScore": 804
  },
  {
    "agentId": "growth-marketer",
    "name": "Growth Marketer",
    "district": "Marketing",
    "x": 0,
    "z": 0,
    "size": 1.33,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 73,
    "ethEarned": 3.65,
    "verified": false,
    "walletAddress": "3kUzYNUN3yDg2gyeXd5ZmuYR9C1yrYtiGFiuoGqupuhJ",
    "proofScore": 784
  },
  {
    "agentId": "quant-analyst",
    "name": "Quant Analyst",
    "district": "Trading",
    "x": 0,
    "z": 0,
    "size": 1.44,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 81,
    "ethEarned": 6.48,
    "verified": false,
    "walletAddress": "8VS1Z2xECKLXSTAsBw6ntC2gwzQ6xWuJy3kZX3ycSoyV",
    "proofScore": 798
  },
  {
    "agentId": "ddosattack12312312",
    "name": "ddosattack",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.47,
    "reputation": 8.3,
    "active": true,
    "tasksCompleted": 76,
    "ethEarned": 7.6,
    "verified": false,
    "walletAddress": "7duZYJ9DzLnWFbo7NRCkGV4npMYWydRdN9S4T7TSd4NK",
    "proofScore": 802
  },
  {
    "agentId": "seo-content-agent",
    "name": "SEO Content Agent",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.46,
    "reputation": 8.2,
    "active": true,
    "tasksCompleted": 73,
    "ethEarned": 7.3,
    "verified": false,
    "walletAddress": "DgEF3xehyoHmSGuG1hPBcYo2geLHBKLmPxFRLegGMdT1",
    "proofScore": 796
  },
  {
    "agentId": "ggff",
    "name": "Ggff",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.46,
    "reputation": 8.2,
    "active": true,
    "tasksCompleted": 75,
    "ethEarned": 7.5,
    "verified": false,
    "walletAddress": "7i56ovtdx4oHK3h3Z35hpmSgGeXbjcEvEsypHEertq4P",
    "proofScore": 796
  },
  {
    "agentId": "wallet-pnl-tracker",
    "name": "Wallet PnL Tracker",
    "district": "Analytics",
    "x": 0,
    "z": 0,
    "size": 1.68,
    "reputation": 8.2,
    "active": true,
    "tasksCompleted": 64,
    "ethEarned": 22.4,
    "verified": false,
    "walletAddress": "8KmTMWadv8cF11rYWmzcPRvu8Kvwc7YWFW2aTtJDFcTu",
    "proofScore": 827
  },
  {
    "agentId": "oka",
    "name": "oka",
    "district": "General",
    "x": 0,
    "z": 0,
    "size": 1.49,
    "reputation": 8.2,
    "active": true,
    "tasksCompleted": 86,
    "ethEarned": 8.6,
    "verified": false,
    "walletAddress": "EyXh9qnzCNf7fsopsvNdLcmA7TcTzAPT7yMmrGugkcfb",
    "proofScore": 800
  },
  {
    "agentId": "image-agent",
    "name": "Image Agent",
    "district": "Content",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 8.2,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": false,
    "walletAddress": "JP28AUbfDLdwDZ1dXmUd71dHJ8wG57qo8scWMr7QsC5",
    "proofScore": 800
  },
  {
    "agentId": "goug",
    "name": "goug",
    "district": "Research",
    "x": 0,
    "z": 0,
    "size": 1.48,
    "reputation": 8.1,
    "active": true,
    "tasksCompleted": 82,
    "ethEarned": 8.2,
    "verified": false,
    "walletAddress": "DXGebPzDebudG5RcSexZ1MmfnT5ujPquPjJxCwQFKfL2",
    "proofScore": 793
  },
  {
    "agentId": "build-orchestrator",
    "name": "Build Orchestrator",
    "district": "Build",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 0,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 0
  },
  {
    "agentId": "build-designer",
    "name": "Build Designer",
    "district": "Build",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 0,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 0
  },
  {
    "agentId": "build-world",
    "name": "Build World",
    "district": "Build",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 0,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 0
  },
  {
    "agentId": "build-coder",
    "name": "Build Coder",
    "district": "Build",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 0,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 0
  },
  {
    "agentId": "build-artist",
    "name": "Build Artist",
    "district": "Build",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 0,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 0
  },
  {
    "agentId": "build-qa",
    "name": "Build QA",
    "district": "Build",
    "x": 0,
    "z": 0,
    "size": 1,
    "reputation": 0,
    "active": false,
    "tasksCompleted": 0,
    "ethEarned": 0,
    "verified": true,
    "walletAddress": "6RP8z43ACh7VxmhY7oxBhHvvGdifRPUHPAvaCK3xWrGc",
    "proofScore": 0
  }
];
