export { AxonApiError, AxonClient } from "./client";
export { verifyWebhookSignature } from "./webhooks";
export type { VerifyWebhookOptions } from "./webhooks";
export { verifyProofScore, verifyReceipt } from "./verify";
export type {
  VerifyProofScoreOptions,
  VerifyProofScoreResult,
  VerifyReceiptOptions,
  VerifyReceiptResult,
} from "./verify";

// High-level agent framework (v0.3): the batteries-included runtime + one-shot hire.
export { defineAgent } from "./runtime";
export { hire } from "./hire";

// Agent checkout (v0.6): your agents propose real purchases, you sign them.
export { CommerceApi, CommerceRefusedError, parseAuthorisation, assertAuthorisationMatches } from "./commerce";

// Axon as LLM tools (v0.4): drop the marketplace into any function-calling agent.
export { buildAxonTools, toOpenAITools, toAnthropicTools, runAxonTool } from "./tools";
export type {
  Agent,
  RegisterOptions,
  FindAgentsOptions,
  VerifyOptions,
  SendTaskOptions,
  TaskStatus,
  TaskRequest,
  TaskResult,
  TaskHandler,
  GetTaskHistoryOptions,
  DelegateOptions,
  WorkflowStep,
  Workflow,
  DelegationResult,
  DelegationStep,
  QuorumStatus,
  QuorumTask,
  QuorumResult,
  CreateQuorumOptions,
  TaskProgress,
  Reputation,
  Transaction,
  GetTransactionsOptions,
  CapabilitySummary,
  AxonConfig,
  McpServer,
  McpToolRecord,
  RegisterMcpServerOptions,
  CallMcpToolOptions,
  X402Requirements,
  X402PaymentOption,
  X402PayFunction,
  Webhook,
  WebhookDelivery,
  WebhookEventType,
  RegisterWebhookOptions,
  GatewayProvider,
  EndpointUptime,
  RegisterGatewayProviderOptions,
  GatewayCallOptions,
  GatewayCallResult,
  ApiErrorBody,
  ApiErrorCode,
  AuthChallenge,
  AuthVerifyResult,
  AgentMetrics,
  AgentBalance,
  PaymentStatus,
  ReceiptDelivery,
  Receipt,
  PaymentNote,
  PaymentNoteKind,
  Review,
  AgentRating,
  OpenTask,
  Bid,
  OpenTaskStatus,
  BidStatus,
  CreateOpenTaskOptions,
  ListOpenTasksOptions,
  SubmitBidOptions,
  AcceptBidOptions,
  SplitRecipient,
  TaskSplit,
  SplitPayout,
  TaskSplitsView,
  DefineSplitsOptions,
  WorkflowTemplate,
  CreateWorkflowTemplateOptions,
  InstantiateTemplateOptions,
  CapabilityAttestation,
  AttestCapabilityOptions,
  SlaStatus,
  TaskSla,
  DefineSlaOptions,
  AbuseReason,
  AbuseStatus,
  AbuseReport,
  FileAbuseReportOptions,
  FeeTier,
  FeePolicy,
  ProtocolInfo,
  ProtocolNegotiation,
  ExplorerTask,
  ExplorerSettlement,
  ExplorerFeed,
  ComponentStatus,
  SystemStatus,
  AgentContext,
  AgentRunHandler,
  AgentRuntimeOptions,
  AxonAgent,
  HireOptions,
  HireResult,
  RunOptions,
  RunResult,
  RouteHireOptions,
  RoutingInfo,
  PlanOptions,
  PlanResult,
  PlanView,
  PlannedStep,
  SubcontractOptions,
  SubcontractResult,
  OptimizeResult,
  AxonTool,
  AxonToolsOptions,
  CommerceProfile,
  CreateProfileOptions,
  SpendMandate,
  GrantMandateOptions,
  PurchaseIntent,
  PurchaseStatus,
  SpendSummary,
  ListPurchasesOptions,
  PurchasesView,
  ApprovalRequest,
  ParsedAuthorisation,
  PurchaseExpectation,
  SignMandate,
  PaymentInstrument,
  PaymentHandlerDescriptor,
  PaymentOptionsView,
  ApproveOptions,
  ApproveResult,
  WatchPurchasesOptions,
  WatchHandle,
  AutoApprovePolicy,
} from "./types";

import { AxonClient } from "./client";

export const axon = new AxonClient();
