-- Baseline schema for Axon.
--
-- This file is the single source of truth for the full DB structure.
-- New installations get everything from here. Existing installations skip
-- tables/indexes that already exist (all statements are IF NOT EXISTS).
--
-- Do NOT edit this file after it has been applied to any database.
-- All future schema changes belong in a new numbered migration file.

-- ── Agents ────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS agents (
  agent_id            TEXT PRIMARY KEY,
  name                TEXT NOT NULL,
  capabilities        TEXT NOT NULL,
  public_key          TEXT NOT NULL,
  endpoint            TEXT,
  price               TEXT,
  reputation          REAL NOT NULL DEFAULT 0,
  category            TEXT NOT NULL DEFAULT 'General',
  wallet_address      TEXT,
  provider            TEXT NOT NULL DEFAULT 'anthropic',
  provider_model      TEXT,
  provider_endpoint   TEXT,
  verification_status TEXT NOT NULL DEFAULT 'unverified',
  last_verified_at    TEXT,
  created_at          TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_capabilities (
  capability  TEXT NOT NULL,
  agent_id    TEXT NOT NULL,
  PRIMARY KEY (capability, agent_id),
  FOREIGN KEY (agent_id) REFERENCES agents(agent_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_capabilities_cap
  ON agent_capabilities(capability);

CREATE TABLE IF NOT EXISTS agent_metrics (
  agent_id         TEXT NOT NULL,
  window_start     TEXT NOT NULL,
  total_tasks      INTEGER NOT NULL DEFAULT 0,
  completed        INTEGER NOT NULL DEFAULT 0,
  failed           INTEGER NOT NULL DEFAULT 0,
  total_latency_ms INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (agent_id, window_start),
  FOREIGN KEY (agent_id) REFERENCES agents(agent_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_agent_metrics_agent
  ON agent_metrics(agent_id, window_start);

CREATE TABLE IF NOT EXISTS agent_budgets (
  budget_id          TEXT PRIMARY KEY,
  agent_id           TEXT NOT NULL,
  name               TEXT,
  max_per_call_usdc  REAL,
  max_per_day_usdc   REAL,
  allowed_to_agents  TEXT,
  status             TEXT NOT NULL DEFAULT 'active',
  created_at         TEXT NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES agents(agent_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_budgets_agent
  ON agent_budgets(agent_id);

-- ── Auth ──────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS challenges (
  id          TEXT PRIMARY KEY,
  agent_id    TEXT NOT NULL,
  value       TEXT NOT NULL,
  expires_at  INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS api_keys (
  key_id         TEXT PRIMARY KEY,
  wallet_address TEXT NOT NULL,
  key_hash       TEXT NOT NULL UNIQUE,
  key_prefix     TEXT NOT NULL,
  created_at     TEXT NOT NULL,
  last_used_at   TEXT
);

CREATE INDEX IF NOT EXISTS idx_api_keys_wallet ON api_keys(wallet_address);
CREATE INDEX IF NOT EXISTS idx_api_keys_hash   ON api_keys(key_hash);

-- ── Tasks ─────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tasks (
  task_id           TEXT PRIMARY KEY,
  from_agent        TEXT NOT NULL,
  to_agent          TEXT NOT NULL,
  task              TEXT NOT NULL,
  context           TEXT,
  payment           TEXT,
  status            TEXT NOT NULL DEFAULT 'queued',
  output            TEXT,
  error             TEXT,
  signature         TEXT,
  workflow_id       TEXT,
  step_index        INTEGER,
  idempotency_scope TEXT,
  idempotency_key   TEXT,
  idempotency_hash  TEXT,
  created_at        TEXT NOT NULL,
  started_at        TEXT,
  started_by        TEXT,
  completed_at      TEXT
);

CREATE INDEX IF NOT EXISTS idx_tasks_to_agent
  ON tasks(to_agent, status);
CREATE INDEX IF NOT EXISTS idx_tasks_from_agent
  ON tasks(from_agent);
CREATE INDEX IF NOT EXISTS idx_tasks_status_created
  ON tasks(status, created_at);
CREATE INDEX IF NOT EXISTS idx_tasks_to_agent_created
  ON tasks(to_agent, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_idempotency
  ON tasks(idempotency_scope, idempotency_key)
  WHERE idempotency_scope IS NOT NULL AND idempotency_key IS NOT NULL;

-- ── Workflows ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS workflows (
  workflow_id    TEXT PRIMARY KEY,
  from_agent     TEXT NOT NULL,
  agents         TEXT NOT NULL,
  initial_task   TEXT NOT NULL,
  status         TEXT NOT NULL DEFAULT 'running',
  current_step   INTEGER NOT NULL DEFAULT 0,
  final_output   TEXT,
  mpp_channel_id TEXT,
  created_at     TEXT NOT NULL,
  completed_at   TEXT
);

CREATE INDEX IF NOT EXISTS idx_workflows_from_agent
  ON workflows(from_agent);

-- ── Payments ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS transactions (
  tx_id              TEXT PRIMARY KEY,
  task_id            TEXT,
  from_agent         TEXT NOT NULL,
  to_agent           TEXT NOT NULL,
  amount_sol         REAL NOT NULL,
  status             TEXT NOT NULL DEFAULT 'escrow',
  signature          TEXT,
  incoming_signature TEXT,
  fee_amount         REAL NOT NULL DEFAULT 0,
  currency           TEXT NOT NULL DEFAULT 'USDC',
  created_at         TEXT NOT NULL,
  settled_at         TEXT
);

CREATE INDEX IF NOT EXISTS idx_transactions_to_agent
  ON transactions(to_agent);
CREATE INDEX IF NOT EXISTS idx_transactions_from_agent
  ON transactions(from_agent);
CREATE INDEX IF NOT EXISTS idx_transactions_task_id
  ON transactions(task_id);
CREATE INDEX IF NOT EXISTS idx_transactions_status_created
  ON transactions(status, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_transactions_incoming_sig
  ON transactions(incoming_signature)
  WHERE incoming_signature IS NOT NULL;

-- ── MPP channels ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS mpp_channels (
  channel_id         TEXT PRIMARY KEY,
  owner_address      TEXT NOT NULL,
  key_hash           TEXT NOT NULL,
  balance_usdc       REAL NOT NULL DEFAULT 0,
  balance_micro_usdc INTEGER NOT NULL DEFAULT 0,
  status             TEXT NOT NULL DEFAULT 'open',
  created_at         TEXT NOT NULL,
  updated_at         TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mpp_owner
  ON mpp_channels(owner_address);
CREATE INDEX IF NOT EXISTS idx_mpp_channels_status
  ON mpp_channels(status, updated_at);

CREATE TABLE IF NOT EXISTS mpp_debits (
  debit_id          TEXT PRIMARY KEY,
  channel_id        TEXT NOT NULL,
  agent_id          TEXT NOT NULL,
  amount_usdc       REAL NOT NULL,
  amount_micro_usdc INTEGER NOT NULL DEFAULT 0,
  task_id           TEXT,
  created_at        TEXT NOT NULL,
  FOREIGN KEY (channel_id) REFERENCES mpp_channels(channel_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mpp_debits_channel ON mpp_debits(channel_id);
CREATE INDEX IF NOT EXISTS idx_mpp_debits_task    ON mpp_debits(task_id);

CREATE TABLE IF NOT EXISTS mpp_deposits (
  deposit_id        TEXT PRIMARY KEY,
  channel_id        TEXT NOT NULL,
  amount_usdc       REAL NOT NULL,
  amount_micro_usdc INTEGER NOT NULL DEFAULT 0,
  signature         TEXT NOT NULL,
  created_at        TEXT NOT NULL,
  FOREIGN KEY (channel_id) REFERENCES mpp_channels(channel_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mpp_deposits_sig
  ON mpp_deposits(signature);
CREATE INDEX IF NOT EXISTS idx_mpp_deposits_channel
  ON mpp_deposits(channel_id);

-- ── Reviews & reputation ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS reviews (
  review_id   TEXT PRIMARY KEY,
  agent_id    TEXT NOT NULL,
  reviewer_id TEXT NOT NULL,
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TEXT NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES agents(agent_id) ON DELETE CASCADE,
  UNIQUE (agent_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_agent_id ON reviews(agent_id);

-- ── Audit log ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit_events (
  audit_id       TEXT PRIMARY KEY,
  actor_wallet   TEXT NOT NULL,
  actor_key_id   TEXT,
  action         TEXT NOT NULL,
  resource_type  TEXT NOT NULL,
  resource_id    TEXT NOT NULL,
  owner_agent_id TEXT,
  owner_wallet   TEXT,
  ip             TEXT,
  metadata       TEXT,
  created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_owner_wallet
  ON audit_events(owner_wallet, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_owner_agent
  ON audit_events(owner_agent_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_resource
  ON audit_events(resource_type, resource_id, created_at);

-- ── Webhooks ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS webhooks (
  webhook_id      TEXT PRIMARY KEY,
  agent_id        TEXT NOT NULL,
  url             TEXT NOT NULL,
  secret          TEXT NOT NULL,
  events          TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'active',
  failure_count   INTEGER NOT NULL DEFAULT 0,
  last_success_at TEXT,
  last_failure_at TEXT,
  disabled_at     TEXT,
  disabled_reason TEXT,
  created_at      TEXT NOT NULL,
  FOREIGN KEY (agent_id) REFERENCES agents(agent_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_webhooks_agent
  ON webhooks(agent_id);
CREATE INDEX IF NOT EXISTS idx_webhooks_status
  ON webhooks(status, failure_count);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  delivery_id     TEXT PRIMARY KEY,
  webhook_id      TEXT NOT NULL,
  event_type      TEXT NOT NULL,
  payload         TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending',
  attempts        INTEGER NOT NULL DEFAULT 0,
  next_attempt_at TEXT NOT NULL,
  last_attempt_at TEXT,
  response_status INTEGER,
  response_body   TEXT,
  created_at      TEXT NOT NULL,
  FOREIGN KEY (webhook_id) REFERENCES webhooks(webhook_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_deliveries_pending
  ON webhook_deliveries(status, next_attempt_at)
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_webhook
  ON webhook_deliveries(webhook_id, created_at);

-- ── MCP servers ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS mcp_servers (
  server_id      TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  endpoint       TEXT NOT NULL,
  description    TEXT,
  owner_agent_id TEXT,
  price_per_call TEXT NOT NULL DEFAULT '0.10 USDC',
  status         TEXT NOT NULL DEFAULT 'active',
  created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mcp_servers_status ON mcp_servers(status);

CREATE TABLE IF NOT EXISTS mcp_tools (
  tool_id      TEXT PRIMARY KEY,
  server_id    TEXT NOT NULL,
  name         TEXT NOT NULL,
  description  TEXT,
  input_schema TEXT NOT NULL,
  last_synced  TEXT NOT NULL,
  FOREIGN KEY (server_id) REFERENCES mcp_servers(server_id) ON DELETE CASCADE,
  UNIQUE (server_id, name)
);

CREATE INDEX IF NOT EXISTS idx_mcp_tools_server ON mcp_tools(server_id);

-- ── Gateway providers ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gateway_providers (
  provider_id     TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  endpoint        TEXT NOT NULL,
  method          TEXT NOT NULL DEFAULT 'POST',
  forward_headers TEXT NOT NULL DEFAULT '[]',
  inject_headers  TEXT NOT NULL DEFAULT '{}',
  price_per_call  TEXT NOT NULL DEFAULT '0.10 USDC',
  description     TEXT,
  owner_agent_id  TEXT,
  timeout_ms      INTEGER NOT NULL DEFAULT 30000,
  status          TEXT NOT NULL DEFAULT 'active',
  created_at      TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gateway_status ON gateway_providers(status);

-- ── Buyback locks ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS buyback_locks (
  lock_id    TEXT PRIMARY KEY,
  agent_id   TEXT NOT NULL,
  tx_id      TEXT NOT NULL,
  amount     REAL NOT NULL,
  currency   TEXT NOT NULL DEFAULT 'USDC',
  locked_at  TEXT NOT NULL,
  unlocks_at TEXT NOT NULL,
  status     TEXT NOT NULL DEFAULT 'pending',
  FOREIGN KEY (agent_id) REFERENCES agents(agent_id)
);

CREATE INDEX IF NOT EXISTS idx_buyback_agent ON buyback_locks(agent_id);
CREATE INDEX IF NOT EXISTS idx_buyback_tx    ON buyback_locks(tx_id);
