export { AxonApiError, AxonClient } from "./client";
export type {
  Agent,
  RegisterOptions,
  FindAgentsOptions,
  VerifyOptions,
  SendTaskOptions,
  TaskStatus,
  TaskRequest,
  TaskResult,
  TaskHandler,
  GetTaskHistoryOptions,
  DelegateOptions,
  WorkflowStep,
  Workflow,
  DelegationResult,
  DelegationStep,
  Reputation,
  Transaction,
  GetTransactionsOptions,
  CapabilitySummary,
  AxonConfig,
  McpServer,
  McpToolRecord,
  RegisterMcpServerOptions,
  CallMcpToolOptions,
  X402Requirements,
  X402PaymentOption,
  X402PayFunction,
  Webhook,
  WebhookDelivery,
  WebhookEventType,
  RegisterWebhookOptions,
  GatewayProvider,
  RegisterGatewayProviderOptions,
  GatewayCallOptions,
  GatewayCallResult,
  ApiErrorBody,
  ApiErrorCode,
} from "./types";

import { AxonClient } from "./client";

export const axon = new AxonClient();
