name: Scheduled public release

on:
  workflow_dispatch:
  schedule:
    - cron: "40 17 14 6 *"

jobs:
  push-to-public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to public repo
        run: |
          git remote add public https://x-access-token:${{ secrets.PUBLIC_REPO_PAT }}@github.com/SeierkDev/Axon.git
          git push public main
